import { icon } from '../../design-system/iconRegistry.js'
import { escapeHtml } from '../../shared/html/escapeHtml.js'
function startOfToday() { const today = new Date(); today.setHours(0, 0, 0, 0); return today }
function formatLongDate(date) { return new Intl.DateTimeFormat('it-IT', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }).format(date) }
function matchTypeLabel(value) { return ({ friendly: 'Amichevole', cup: 'Coppa', league: 'Campionato' })[value] || 'Partita' }

export function renderDashboardView(calendarEvents = [], team = {}) {
  const now = new Date(); const today = startOfToday(); const day = (today.getDay() + 6) % 7
  const weekStart = new Date(today); weekStart.setDate(today.getDate() - day)
  const weekEnd = new Date(weekStart); weekEnd.setDate(weekStart.getDate() + 7)
  const weekEvents = calendarEvents.filter((event) => { const date = new Date(event.startAt); return date >= weekStart && date < weekEnd }).sort((a,b)=>new Date(a.startAt)-new Date(b.startAt))
  const weeklyTrainings = weekEvents.filter((event) => event.type === 'training')
  const nextMatches = calendarEvents.filter((event) => event.type === 'match' && new Date(event.startAt) >= now).sort((a,b)=>new Date(a.startAt)-new Date(b.startAt)).slice(0,3)
  const dayDiff = (from,to) => { const start=new Date(from); const end=new Date(to); start.setHours(0,0,0,0); end.setHours(0,0,0,0); return Math.max(0,Math.round((end-start)/86400000)) }
  const weekDays = Array.from({length:7},(_,index)=>{ const date=new Date(weekStart); date.setDate(weekStart.getDate()+index); return {date,events:weekEvents.filter((event)=>new Date(event.startAt).toDateString()===date.toDateString())} })

  return `<section class="view page-view dashboard-professional">
    <div class="page-head"><div><h1>Dashboard</h1><p><span>${escapeHtml(team.season ? `STAGIONE ${team.season}` : 'STAGIONE')}</span><b>•</b>Panoramica operativa</p></div></div>
    <div class="dashboard-primary-grid">
      <article class="dashboard-feature-card dashboard-next-match"><div class="dashboard-card-kicker">PROSSIME PARTITE</div>${nextMatches.length ? `<div class="dashboard-match-list">${nextMatches.map((match,index)=>{ const previous=index===0?today:new Date(nextMatches[index-1].startAt); const distance=dayDiff(previous,new Date(match.startAt)); const distanceLabel=index===0?(distance===0?'Oggi':distance===1?'Domani':`Tra ${distance} giorni`):(distance===1?'1 giorno dalla precedente':`${distance} giorni dalla precedente`); return `<article class="dashboard-match-item"><button type="button" data-open-event="${match.id}" aria-label="Apri ${escapeHtml(match.title || 'partita')}"><div class="dashboard-match-main"><span class="dashboard-match-date">${new Date(match.startAt).toLocaleDateString('it-IT',{weekday:'long',day:'numeric',month:'long'})}</span><strong>${match.time}</strong></div><h2>${escapeHtml(match.title || 'Partita')}</h2><p>${match.matchType?`<span class="match-kind match-kind--${escapeHtml(match.matchType)}">${escapeHtml(matchTypeLabel(match.matchType))}</span>`:''}${escapeHtml(match.place || 'Campo da definire')}</p><small class="dashboard-match-distance">${distanceLabel}</small></button></article>` }).join('')}</div>` : '<div class="dashboard-empty-state">Nessuna partita futura programmata.</div>'}</article>
      <article class="dashboard-feature-card"><div class="dashboard-card-head"><div><span>ALLENAMENTI SETTIMANA</span><h2>${weeklyTrainings.length} sedute</h2></div><b>${weekStart.toLocaleDateString('it-IT',{day:'2-digit',month:'2-digit'})}–${new Date(weekEnd-1).toLocaleDateString('it-IT',{day:'2-digit',month:'2-digit'})}</b></div><div class="dashboard-training-history">${weeklyTrainings.length?weeklyTrainings.map((event)=>`<button type="button" data-open-event="${event.id}"><span>${new Date(event.startAt).toLocaleDateString('it-IT',{weekday:'short',day:'numeric'})}</span><strong>${event.time} · ${escapeHtml(event.place || 'Campo da definire')}</strong><small>${event.matchDay || 'MD —'}${event.trainingSheetPath?' · TS pubblicata':' · TS assente'}</small></button>`).join(''):'<div class="dashboard-empty-state">Nessun allenamento nella settimana corrente.</div>'}</div></article>
    </div>
    <article class="dashboard-week-card"><div class="dashboard-card-head"><div><span>CALENDARIO SETTIMANALE</span><h2>${formatLongDate(today)}</h2></div><button type="button" class="ghost-button" data-dashboard-calendar>Apri calendario</button></div><div class="dashboard-week-grid">${weekDays.map(({date,events})=>`<div class="dashboard-day ${date.toDateString()===today.toDateString()?'is-today':''}"><header><span>${date.toLocaleDateString('it-IT',{weekday:'short'}).toUpperCase()}</span><strong>${date.getDate()}</strong></header><div>${events.length?events.map((event)=>`<button type="button" data-open-event="${event.id}" class="is-${event.type} ${event.type==='match'&&event.matchType?`is-match-${event.matchType}`:''}"><b>${event.time}</b><span>${escapeHtml(event.title)}</span><small>${event.matchDay || escapeHtml(event.place || '')}</small></button>`).join(''):'<em>—</em>'}</div></div>`).join('')}</div></article>
  </section>`
}
