export const ACCESS_ROLES = Object.freeze({
  OWNER: 'owner',
  ADMIN: 'admin',
  COLLABORATOR: 'collaborator',
  READ_ONLY: 'read_only',
})

export const ACCESS_CAPABILITIES = Object.freeze({
  STAFF_VIEW: 'staff.view',
  STAFF_MANAGE: 'staff.manage',
  STAFF_CREATE: 'staff.create',
  STAFF_UPDATE: 'staff.update',
  STAFF_DELETE: 'staff.delete',
  TEAM_IDENTITY_VIEW: 'teamIdentity.view',
  TEAM_IDENTITY_UPDATE: 'teamIdentity.update',
  CALENDAR_VIEW: 'calendar.view',
  CALENDAR_CREATE: 'calendar.create',
  CALENDAR_UPDATE: 'calendar.update',
  CALENDAR_DELETE: 'calendar.delete',
  TRAINING_SHEET_VIEW: 'trainingSheet.view',
  TRAINING_SHEET_VIEW_PUBLISHED: 'trainingSheet.viewPublished',
  TRAINING_SHEET_CREATE: 'trainingSheet.create',
  TRAINING_SHEET_EDIT: 'trainingSheet.edit',
  TRAINING_SHEET_PUBLISH: 'trainingSheet.publish',
  TRAINING_SHEET_DELETE: 'trainingSheet.delete',
  MATCH_LIBRARY_VIEW: 'matchLibrary.view',
  MATCH_SHEET_VIEW: 'matchSheet.view',
  MATCH_STATISTICS_VIEW: 'matchStatistics.view',
  MATCH_SHEET_CREATE: 'matchSheet.create',
  MATCH_SHEET_EDIT: 'matchSheet.edit',
  MATCH_SHEET_PUBLISH: 'matchSheet.publish',
  BOARD_VIEW: 'board.view',
  BOARD_EDIT: 'board.edit',
  ROSTER_VIEW: 'roster.view',
  ROSTER_EDIT: 'roster.edit',
  ANALYSIS_VIEW: 'analysis.view',
  ANALYSIS_IMPORT: 'analysis.import',
  METHODOLOGY_VIEW: 'methodology.view',
  LIBRARY_VIEW: 'library.view',
  PROFILE_VIEW: 'profile.view',
  PROFILE_UPDATE: 'profile.update',
  SPORT_MUTATE: 'sport.mutate',
})

const normalizeToken = (value = '') => String(value)
  .normalize('NFD')
  .replace(/[\u0300-\u036f]/g, '')
  .trim()
  .toLowerCase()
  .replace(/[\s-]+/g, '_')

const ROLE_ALIASES = Object.freeze({
  owner: ACCESS_ROLES.OWNER,
  proprietario: ACCESS_ROLES.OWNER,
  admin: ACCESS_ROLES.ADMIN,
  administrator: ACCESS_ROLES.ADMIN,
  amministratore: ACCESS_ROLES.ADMIN,
  collaborator: ACCESS_ROLES.COLLABORATOR,
  collaboratore: ACCESS_ROLES.COLLABORATOR,
  read_only: ACCESS_ROLES.READ_ONLY,
  readonly: ACCESS_ROLES.READ_ONLY,
  solo_lettura: ACCESS_ROLES.READ_ONLY,
  lettura: ACCESS_ROLES.READ_ONLY,
})

const OWNER_CAPABILITIES = Object.freeze(Object.values(ACCESS_CAPABILITIES))

const ADMIN_CAPABILITIES = Object.freeze([
  ACCESS_CAPABILITIES.STAFF_VIEW,
  ACCESS_CAPABILITIES.STAFF_MANAGE,
  ACCESS_CAPABILITIES.STAFF_CREATE,
  ACCESS_CAPABILITIES.STAFF_UPDATE,
  ACCESS_CAPABILITIES.STAFF_DELETE,
  ACCESS_CAPABILITIES.TEAM_IDENTITY_VIEW,
  ACCESS_CAPABILITIES.CALENDAR_VIEW,
  ACCESS_CAPABILITIES.CALENDAR_CREATE,
  ACCESS_CAPABILITIES.CALENDAR_UPDATE,
  ACCESS_CAPABILITIES.CALENDAR_DELETE,
  ACCESS_CAPABILITIES.TRAINING_SHEET_VIEW,
  ACCESS_CAPABILITIES.TRAINING_SHEET_VIEW_PUBLISHED,
  ACCESS_CAPABILITIES.TRAINING_SHEET_CREATE,
  ACCESS_CAPABILITIES.TRAINING_SHEET_EDIT,
  ACCESS_CAPABILITIES.TRAINING_SHEET_PUBLISH,
  ACCESS_CAPABILITIES.TRAINING_SHEET_DELETE,
  ACCESS_CAPABILITIES.MATCH_LIBRARY_VIEW,
  ACCESS_CAPABILITIES.MATCH_SHEET_VIEW,
  ACCESS_CAPABILITIES.MATCH_STATISTICS_VIEW,
  ACCESS_CAPABILITIES.MATCH_SHEET_CREATE,
  ACCESS_CAPABILITIES.MATCH_SHEET_EDIT,
  ACCESS_CAPABILITIES.MATCH_SHEET_PUBLISH,
  ACCESS_CAPABILITIES.BOARD_VIEW,
  ACCESS_CAPABILITIES.BOARD_EDIT,
  ACCESS_CAPABILITIES.ROSTER_VIEW,
  ACCESS_CAPABILITIES.ROSTER_EDIT,
  ACCESS_CAPABILITIES.ANALYSIS_VIEW,
  ACCESS_CAPABILITIES.ANALYSIS_IMPORT,
  ACCESS_CAPABILITIES.METHODOLOGY_VIEW,
  ACCESS_CAPABILITIES.LIBRARY_VIEW,
  ACCESS_CAPABILITIES.PROFILE_VIEW,
  ACCESS_CAPABILITIES.PROFILE_UPDATE,
  ACCESS_CAPABILITIES.SPORT_MUTATE,
])

const COLLABORATOR_CAPABILITIES = Object.freeze([
  ACCESS_CAPABILITIES.CALENDAR_VIEW,
  ACCESS_CAPABILITIES.CALENDAR_CREATE,
  ACCESS_CAPABILITIES.CALENDAR_UPDATE,
  ACCESS_CAPABILITIES.CALENDAR_DELETE,
  ACCESS_CAPABILITIES.TRAINING_SHEET_VIEW,
  ACCESS_CAPABILITIES.TRAINING_SHEET_VIEW_PUBLISHED,
  ACCESS_CAPABILITIES.TRAINING_SHEET_CREATE,
  ACCESS_CAPABILITIES.TRAINING_SHEET_EDIT,
  ACCESS_CAPABILITIES.TRAINING_SHEET_PUBLISH,
  ACCESS_CAPABILITIES.TRAINING_SHEET_DELETE,
  ACCESS_CAPABILITIES.MATCH_LIBRARY_VIEW,
  ACCESS_CAPABILITIES.MATCH_SHEET_VIEW,
  ACCESS_CAPABILITIES.MATCH_STATISTICS_VIEW,
  ACCESS_CAPABILITIES.MATCH_SHEET_CREATE,
  ACCESS_CAPABILITIES.MATCH_SHEET_EDIT,
  ACCESS_CAPABILITIES.MATCH_SHEET_PUBLISH,
  ACCESS_CAPABILITIES.BOARD_VIEW,
  ACCESS_CAPABILITIES.BOARD_EDIT,
  ACCESS_CAPABILITIES.ROSTER_VIEW,
  ACCESS_CAPABILITIES.ROSTER_EDIT,
  ACCESS_CAPABILITIES.ANALYSIS_VIEW,
  ACCESS_CAPABILITIES.ANALYSIS_IMPORT,
  ACCESS_CAPABILITIES.METHODOLOGY_VIEW,
  ACCESS_CAPABILITIES.LIBRARY_VIEW,
  ACCESS_CAPABILITIES.PROFILE_VIEW,
  ACCESS_CAPABILITIES.PROFILE_UPDATE,
  ACCESS_CAPABILITIES.SPORT_MUTATE,
])

const READ_ONLY_CAPABILITIES = Object.freeze([
  ACCESS_CAPABILITIES.CALENDAR_VIEW,
  ACCESS_CAPABILITIES.TRAINING_SHEET_VIEW,
  ACCESS_CAPABILITIES.TRAINING_SHEET_VIEW_PUBLISHED,
  ACCESS_CAPABILITIES.MATCH_LIBRARY_VIEW,
  ACCESS_CAPABILITIES.MATCH_SHEET_VIEW,
  ACCESS_CAPABILITIES.MATCH_STATISTICS_VIEW,
  ACCESS_CAPABILITIES.ROSTER_VIEW,
  ACCESS_CAPABILITIES.ANALYSIS_VIEW,
  ACCESS_CAPABILITIES.METHODOLOGY_VIEW,
  ACCESS_CAPABILITIES.LIBRARY_VIEW,
  ACCESS_CAPABILITIES.PROFILE_VIEW,
  ACCESS_CAPABILITIES.PROFILE_UPDATE,
])

const ROLE_CAPABILITIES = Object.freeze({
  [ACCESS_ROLES.OWNER]: new Set(OWNER_CAPABILITIES),
  [ACCESS_ROLES.ADMIN]: new Set(ADMIN_CAPABILITIES),
  [ACCESS_ROLES.COLLABORATOR]: new Set(COLLABORATOR_CAPABILITIES),
  [ACCESS_ROLES.READ_ONLY]: new Set(READ_ONLY_CAPABILITIES),
})

export const FROZEN_PRODUCT_SECTIONS = Object.freeze(['board', 'methodology'])
const FROZEN_PRODUCT_SECTION_SET = new Set(FROZEN_PRODUCT_SECTIONS)

const SECTION_CAPABILITY = Object.freeze({
  dashboard: null,
  calendar: ACCESS_CAPABILITIES.CALENDAR_VIEW,
  'training-sheet': ACCESS_CAPABILITIES.TRAINING_SHEET_EDIT,
  library: ACCESS_CAPABILITIES.LIBRARY_VIEW,
  'match-library': ACCESS_CAPABILITIES.MATCH_LIBRARY_VIEW,
  'match-workspace': ACCESS_CAPABILITIES.MATCH_LIBRARY_VIEW,
  callups: ACCESS_CAPABILITIES.ROSTER_VIEW,
  'our-team': ACCESS_CAPABILITIES.MATCH_SHEET_EDIT,
  opponent: ACCESS_CAPABILITIES.MATCH_SHEET_EDIT,
  'match-statistics': ACCESS_CAPABILITIES.MATCH_STATISTICS_VIEW,
  'opponent-study': ACCESS_CAPABILITIES.MATCH_LIBRARY_VIEW,
  'match-report-workspace': ACCESS_CAPABILITIES.MATCH_LIBRARY_VIEW,
  'post-match': ACCESS_CAPABILITIES.MATCH_LIBRARY_VIEW,
  board: ACCESS_CAPABILITIES.BOARD_EDIT,
  squad: ACCESS_CAPABILITIES.ROSTER_VIEW,
  analysis: ACCESS_CAPABILITIES.ANALYSIS_VIEW,
  methodology: ACCESS_CAPABILITIES.METHODOLOGY_VIEW,
  settings: ACCESS_CAPABILITIES.STAFF_VIEW,
  staff: ACCESS_CAPABILITIES.STAFF_VIEW,
  'team-settings': ACCESS_CAPABILITIES.TEAM_IDENTITY_UPDATE,
  profile: ACCESS_CAPABILITIES.PROFILE_VIEW,
})

export function normalizeAccessRole(role) {
  return ROLE_ALIASES[normalizeToken(role)] || ACCESS_ROLES.READ_ONLY
}

export function canForRole(role, capability) {
  if (!capability) return true
  return ROLE_CAPABILITIES[normalizeAccessRole(role)]?.has(capability) === true
}

export function getAccessPolicy(role) {
  const normalizedRole = normalizeAccessRole(role)
  return Object.freeze({
    role: normalizedRole,
    manageStaff: canForRole(normalizedRole, ACCESS_CAPABILITIES.STAFF_MANAGE),
    manageTeam: canForRole(normalizedRole, ACCESS_CAPABILITIES.TEAM_IDENTITY_UPDATE),
    mutateSport: canForRole(normalizedRole, ACCESS_CAPABILITIES.SPORT_MUTATE),
  })
}

export function canAccessSectionForRole(role, sectionKey) {
  if (FROZEN_PRODUCT_SECTION_SET.has(sectionKey)) return false
  if (!(sectionKey in SECTION_CAPABILITY)) return false
  return canForRole(role, SECTION_CAPABILITY[sectionKey])
}

export function filterMenuForRole(menu, role) {
  return menu.filter(([sectionKey]) => canAccessSectionForRole(role, sectionKey))
}

export function firstAccessibleSection(menu, role, preferred = 'dashboard') {
  if (canAccessSectionForRole(role, preferred)) return preferred
  return filterMenuForRole(menu, role)[0]?.[0] || 'profile'
}
